# Generated by Django 5.2.10 on 2026-01-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_utilisateur_adresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='localisation',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
