# Generated by Django 5.2.10 on 2026-01-17 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_utilisateur_localisation_utilisateur_adresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrepot',
            name='localisation',
        ),
        migrations.AddField(
            model_name='entrepot',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepot',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='entrepot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.entrepot'),
        ),
    ]
