# Generated by Django 5.2.10 on 2026-01-17 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_entrepot_localisation_entrepot_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ordre', models.JSONField(help_text='Liste ordonnée des IDs de livraisons')),
                ('distance_totale', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='mouvementstock',
            options={},
        ),
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'ordering': ['nom', 'prenom']},
        ),
        migrations.RemoveIndex(
            model_name='mouvementstock',
            name='idx_mouvement_date',
        ),
        migrations.RemoveIndex(
            model_name='mouvementstock',
            name='idx_mouvement_type',
        ),
        migrations.RemoveField(
            model_name='mouvementstock',
            name='commentaire',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='entrepot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='core.entrepot'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='grossiste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='numero',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('PREPARATION', 'Préparation'), ('EN_ROUTE', 'En route'), ('LIVREE', 'Livrée')], default='PREPARATION', max_length=20),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='destination_emplacement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrees', to='core.emplacement'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='core.lot'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='quantite',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='source_emplacement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorties', to='core.emplacement'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('TRANSFERT', 'Transfert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournee',
            name='entrepot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entrepot'),
        ),
        migrations.AddField(
            model_name='tournee',
            name='livreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
