# Generated by Django 5.2.10 on 2026-01-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_utilisateur_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='adresse',
        ),
    ]
